apiVersion: v1
kind: Service
metadata:
  name: grocerybackend
spec:
  type: NodePort
  selector:
    app: component-grocerybackend
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocerybackend
spec:
  selector:
    matchLabels:
      app: component-grocerybackend
  template:
    metadata:
      labels:
        app: component-grocerybackend
    spec:
      containers:
      - name: grocery-backend
        image: tobespc/grocerybackend
        imagePullPolicy: Always
        ports:
        - containerPort: 9080